### ISSUE TITLE
Properties as Table like function properties

### ISSUE THREAD

**Issue by ozum** [typedoc2md/typedoc-plugin-markdown#109]
Hi,

Is it possible to document interface parameters like function properties as a table instead of listed one by one.

The reason I'm asking is that, I'm using typedoc to create README.md files and interface parameters make the page very long.

Thanks,

**Comment by capraynor** [comment]
Hi, @ozum @tgreyuk

The requirement might be different from different case. 

Some project's API document (property comments) are simple (one-line), so that project might need a property-table markdown description to make the document clean & tidy. 

However, some project's API document are complex (like they needs to include a example-code-comment inside the property comment). 
In this situation, the comment is a multi-line comment. 
Due to the markdown table has poor support for multiline-text, 
So markdown table may not fit this situation. 
So the list mode is still needed in this situation. 

If someone is willing to implement this, I suggest to provide a configuration to switch the document style:
 
Table mode, that render the properties to table, which fits the one-line comment in properties. 

List mode, that render the properties to a list (current behavior), witch fits the multi line comments in properties.

**Comment by tgreyuk** [comment]
https://www.typedoc-plugin-markdown.org/docs/options#propertiesformat
