### ISSUE TITLE
Overloaded class properties should be printed as separate items.

### ISSUE THREAD

**Issue by Huxpro** [typedoc2md/typedoc-plugin-markdown#718]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

Source code:

```
export interface Foo { 
  getJSModule<Module = unknown>(name: string): Module;
  getJSModule(name: "GlobalEventEmitter"): GlobalEventEmitter;
}
```

Actual behaviors:

![image](https://github.com/user-attachments/assets/9950587d-263c-40a3-95cc-3cb742fd1ca5)

Expected behaviors:

Overloaded class properties should be printed as separate items.

### TypeDoc configuration

Originally I thought this is a TypeDoc issue: https://github.com/TypeStrong/typedoc/issues/2767

But it seems like it's largely defined by the markdownTheme here.

A default configuration should be able to reproduce this issue.

### Expected behavior

Overloaded class properties should be printed as separate items like TypeDoc html theme: https://github.com/TypeStrong/typedoc/issues/2767

**Comment by tgreyuk** [comment]
@Huxpro  Thanks. see `typedoc-plugin-markdown@4.3.0`.

Overloaded props are now printed in separate sections, but in order to maintain integrity of headers we have introduced the translatable heading "Call Signature" to each overload.

Example: 

https://github.com/typedoc2md/typedoc-plugin-markdown-scratchpad/blob/main/issues/718/docs/md/interfaces/Foo.md

Screenshot:

<img width="676" alt="Screenshot 2024-11-27 at 19 52 51" src="https://github.com/user-attachments/assets/c10ec9d4-6948-4794-9a86-f2f5ac778133">
